url: https://tmcdc.org/
baseurl: 

# Site settings
title: Thurgood Marshall Child Development Center
email: director@tmcdc.org
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

about: "<p>We provide quality care for children ages 3 months until kindergarten.</p>
<p>Our center offers warm, friendly, professionally-organized, unique child care in the heart of the nation's capital, just steps from Union Station in Washington, D.C.  We strive to create a loving community of children, parents, teachers, and friends.</p>
<p>Our staff include talented, highly trained, and academically credentialed teachers who nurture and facilitate integrated learning, following a child's own rhythms.  Our responsive teachers understand that children are learning all the time through active and purposeful involvement with people, materials, and ideas.</p>
<p>We use the Creative Curriculum, a play-orientated, child-initiated approach.  The Creative Curriculum fosters a dynamic environment to satisfy the young child's natural sense of wonder, sociability, eagerness to explore and problem solve, enthusiasm for quality literature, and aptitude to learn through play.</p>
<p>In addition to classroom experiences, children play on our large, private outdoor playground, go on neighborhood walks, and have the option to take field trips to exciting destinations.  We also offer enrichment programs in Spanish, music, and gymnastics.</p>
<p>We see parents and teachers as partners, and value close, regular, and open communication.  Our environment respects individuality and differences.  We have an open door policy, and parents are welcome to visit anytime.</p>"

# Team names, titles and social links
people:
#- name: Janine Fetters
#  pic: 5
#  position: Executive Director
#  email: director@tmcdc.org
#  social:
#     - title: intagram
#       url: https://www.instagram.com/tmcdc/
#     - title: facebook
#       url: https://www.facebook.com/Thurgood-Marshall-Child-Development-Center-982569225163458/
#     - title: stack-overflow
#       url: #

- name: Kiysha Ramey-Jenkins
  pic: k
  position: Associate Director
  email: Kiysha@tmcdc.org
  social:
     - title: instagram
       url: https://www.instagram.com/tmcdc/
     - title: facebook
       url: https://www.facebook.com/Thurgood-Marshall-Child-Development-Center-982569225163458/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Thurgood-Marshall-Child-Development-Center-982569225163458/
  - title: instagram
    url: https://www.instagram.com/tmcdc/

# Postal address (add as many lines as necessary)
address:
  - line: Thurgood Marshall Federal Judiciary Building
  - line: One Columbus Circle, NE
  - line: Suite M-200
  - line: Washington, DC 20544

contact:
  description: Please contact us for more information about the Center. Our staff are ready to answer any questions you may have.

  location:
    -
      name: Thurgood Marshall Federal Judiciary Building
      address1: One Columbus Circle NE
      address2: Suite M-200
      city: Washington
      state: DC
      zipCode: 20544

  phone: +1.202.502.2475

# Build settings
livereload: true
markdown: kramdown
permalink: pretty
